pipeline:
  name: AM-build
  identifier: AMbuild
  projectIdentifier: IDA
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: AM-build
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: api
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: setup
                  identifier: setup
                  spec:
                    connectorRef: account.harnessImage
                    image: gtbanf1979/maven:v1
                    shell: Sh
                    command: |-
                      mkdir /harness/AM
                      curl -k https://192.168.1.83:8443/repository/adhoc/Ping/AM/AM-7.4.0.zip -O --output-dir /harness/AM/
                      cd /harness/AM/
                      unzip AM-7.4.0.zip
                      pwd
                      ls -la .
                      cd /harness/AM/openam/samples/docker/
                      chmod +x ./setup.sh
                      ./setup.sh
                      cd images/am-empty
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Nexus
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.Nexus
                    repo: 192.168.1.83:5000/repository/am-empty
                    tags: <+input>
                    dockerfile: <+input>
                    context: /harness/AM/openam/samples/docker/images/am-empty
                    buildArgs:
                      APP_NAME: <+pipeline.name>
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1
                    envVariables:
                      PLUGIN_SKIP_TLS_VERIFY: "true"
